name: PR Workflow
on:
  pull_request:
    types: [closed]
    branches:
    - master

jobs:
  closePullRequestJob:
    if: (github.event_name == 'pull_request' && github.event.action == 'closed')
    runs-on: windows-latest
    steps:
      
      # get values of the PR and store in env var
      - name: Get PR values
        uses: abelsquidhead/GetPRInfoAction@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
        id: getPRValuesStep

      # delete staging slot
      - name: Delete staging slot
        env:
          SERVICE_PRINCIPAL: http://AbelDeployDemoBackupPrincipal
          SERVICE_PRINCIPAL_TENANT: 72f988bf-86f1-41af-91ab-2d7cd011db47
          RESOURCE_GROUP: forhanselman-rg
          WEB_APP_NAME: AbelTestWebApp
        run: |
          az login --service-principal --username %SERVICE_PRINCIPAL% --password ${{ secrets.SERVICE_PRINCIPAL_SECRET }} --tenant %SERVICE_PRINCIPAL_TENANT%
          az webapp deployment slot delete --name %WEB_APP_NAME% --resource-group %RESOURCE_GROUP% --slot staging-pr-${{ steps.getPRValuesStep.outputs.number}}
